apiVersion: v1
kind: Node
metadata:
  name: gpu-node-PLACEHOLDER
  labels:
    type: kwok
    nvidia.com/gpu.count: "64"
    topology.nvidia.com/nvlink-domain: "dom-PLACEHOLDER_DOMAIN"
    topology.kubernetes.io/zone: "zone-PLACEHOLDER_ZONE"
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: "fake"
status:
  capacity:
    cpu: "64"
    memory: 512Gi
    pods: "256"
    nvidia.com/gpu: "64"
  allocatable:
    cpu: "64"
    memory: 512Gi
    pods: "256"
    nvidia.com/gpu: "64"
  nodeInfo:
    kubeletVersion: fake
  conditions:
    - type: Ready
      status: "True"
      reason: KubeletReady
